spring:
  application:
    name: web-service-dev
  dubbo:
    consumer:
      filter: tracing
server:
  port: 5003
dubbo:
  application:
    name: web-service
    qosEnable: false
    qosPort: 7003
    qosAcceptForeignIp: false
  protocol:
    name: dubbo
    port: 6003
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  consumer:
    filter: tracing
  provider:
    filter: tracing
